"""Tests for LongMemEval evidence mining in the converter.

Background
----------

The previous converter hard-coded ``evidence_turn_ids = []`` and only
populated ``evidence_session_ids`` from ``answer_session_ids``. That made
the LME eval a *ranking* test (any session in the answer set was a hit)
rather than a *retrieval* test (did we surface the specific turns the
answer cites?).

The new converter reads real evidence fields from the raw LME case
when present (the xiaowu0162 cleaned variant only carries
``answer_session_ids``; other variants also carry ``evidence_turn_ids``)
behind a feature flag. These tests pin:

* Real evidence flows from raw to eimemory for the cleaned variant.
* Synthetic raw cases that include ``evidence_turn_ids`` propagate the
  turn IDs through to the eimemory output.
* The feature flag controls behaviour; disabling it reproduces the old
  empty-turn-ids behaviour.

The ``data/longmemeval_s_eimemory.json`` snapshot is NOT regenerated by
these tests; the converter is exercised against the raw input only.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONVERTER_PATH = REPO_ROOT / "scripts" / "convert_longmemeval_to_eimemory.py"
DATA_PATH = REPO_ROOT / "data" / "longmemeval_s_cleaned.json"


def _load_converter():
    """Import the converter script as a module (it is in scripts/, not a package)."""
    spec = importlib.util.spec_from_file_location("lme_converter", CONVERTER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _load_raw_sample(limit: int = 1) -> list[dict]:
    raw = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    return raw[:limit]


# ---------------------------------------------------------------------------
# Real-evidence mining on the actual cleaned raw LME data
# ---------------------------------------------------------------------------


def test_lme_converter_emits_real_evidence(tmp_path) -> None:
    """A cleaned-variant raw case must yield non-empty evidence_session_ids."""
    converter = _load_converter()
    raw = _load_raw_sample(limit=1)
    assert raw[0].get("answer_session_ids"), "raw sample missing answer_session_ids"
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 1
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    case = out_data["cases"][0]
    assert case["evidence_session_ids"], "expected non-empty evidence_session_ids"
    assert case["evidence_session_ids"] == raw[0]["answer_session_ids"]
    # The xiaowu0162 cleaned variant has no per-turn evidence; turn IDs
    # are expected to be empty but the field must exist and be a list.
    assert "evidence_turn_ids" in case
    assert case["evidence_turn_ids"] == []


def test_lme_converter_evidence_matches_raw(tmp_path) -> None:
    """The eimemory evidence_session_ids must equal the raw answer_session_ids."""
    converter = _load_converter()
    raw = _load_raw_sample(limit=3)
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 3
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    for raw_case, eim_case in zip(raw, out_data["cases"]):
        assert set(eim_case["evidence_session_ids"]) == set(
            raw_case.get("answer_session_ids") or []
        )
        # The eimemory case_id is the raw question_id.
        assert eim_case["case_id"] == raw_case["question_id"]
        # The eimemory question mirrors the raw question.
        assert eim_case["question"] == raw_case["question"]


# ---------------------------------------------------------------------------
# Synthetic raw case carries per-turn evidence
# ---------------------------------------------------------------------------


def test_lme_converter_propagates_evidence_turn_ids(tmp_path) -> None:
    """When raw carries evidence_turn_ids, they must flow to eimemory."""
    converter = _load_converter()
    raw = [
        {
            "question_id": "syn-1",
            "question": "When did the user move?",
            "question_type": "temporal",
            "question_date": "2024-01-01",
            "answer": "March 2023",
            "answer_session_ids": ["sess-move"],
            "haystack_session_ids": ["sess-move", "sess-other"],
            "haystack_dates": ["2023-03-01", "2023-04-01"],
            "haystack_sessions": [
                [
                    {"role": "user", "content": "I moved in March 2023."},
                ],
                [
                    {"role": "user", "content": "I had dinner."},
                ],
            ],
            "evidence_turn_ids": ["sess-move:m0"],
        }
    ]
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 1
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    case = out_data["cases"][0]
    assert case["evidence_session_ids"] == ["sess-move"]
    assert case["evidence_turn_ids"] == ["sess-move:m0"]
    assert case["meta"]["evidence_mining_enabled"] is True


def test_lme_converter_feature_flag_disables_mining(tmp_path, monkeypatch) -> None:
    """With the flag off, evidence_turn_ids is hard-coded empty again."""
    converter = _load_converter()
    monkeypatch.setattr(converter, "_USE_REAL_EVIDENCE", False)
    raw = [
        {
            "question_id": "syn-2",
            "question": "q?",
            "question_type": "temporal",
            "answer": "a",
            "answer_session_ids": ["sess-x"],
            "haystack_session_ids": ["sess-x"],
            "haystack_dates": ["2024-01-01"],
            "haystack_sessions": [[{"role": "user", "content": "hi"}]],
            "evidence_turn_ids": ["sess-x:m0"],
        }
    ]
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    converter.convert(in_path, out_path)
    case = json.loads(out_path.read_text(encoding="utf-8"))["cases"][0]
    # Flag off -> turn IDs dropped even though raw had them.
    assert case["evidence_turn_ids"] == []
    assert case["meta"]["evidence_mining_enabled"] is False
    # Session-level evidence still flows (it predates the flag).
    assert case["evidence_session_ids"] == ["sess-x"]


def test_lme_converter_extract_real_evidence_helper() -> None:
    """Direct unit test of the extraction helper (no IO)."""
    converter = _load_converter()
    # Both fields populated; helper unions them with dedup.
    ses, turns = converter._extract_real_evidence(
        {
            "answer_session_ids": ["A", "B"],
            "evidence_session_ids": ["B", "C"],
            "evidence_turn_ids": ["t1", "t2"],
        }
    )
    assert ses == ["A", "B", "C"]
    assert turns == ["t1", "t2"]
    # Only answer_session_ids.
    ses, turns = converter._extract_real_evidence({"answer_session_ids": ["only"]})
    assert ses == ["only"]
    assert turns == []
    # Empty case.
    assert converter._extract_real_evidence({}) == ([], [])
