"""Exercise the real bytecode cleaner at the installer's receipt boundary."""
from pathlib import Path
import os
import shlex
import shutil
import subprocess
import sys

import pytest


ROOT = Path(__file__).resolve().parents[1]


def _function(name):
    text = (ROOT / 'deploy/install_immutable_release.sh').read_text()
    marker = name + '() {'
    if marker not in text:
        return ''
    return marker + text.split(marker, 1)[1].split('\n}', 1)[0] + '\n}\n'


def _fixture(tmp_path):
    repo = tmp_path / 'repo'
    repo.mkdir()
    subprocess.run(['git', 'init', '-q', str(repo)], check=True)
    plugin = repo / 'integrations/hermes/eimemory'
    plugin.mkdir(parents=True)
    (plugin / '__init__.py').write_text('VALUE = 1\n')
    deploy = repo / 'deploy'
    deploy.mkdir()
    shutil.copyfile(ROOT / 'deploy/clean_release_bytecode.py', deploy / 'clean_release_bytecode.py')
    (deploy / 'record_deployment_receipt.py').write_text(
        'import os\nfrom pathlib import Path\n'
        'root = Path(os.environ["TEST_RELEASE"])\n'
        'assert not list((root / "integrations").rglob("__pycache__")), "runtime bytecode remains"\n'
        'print("receipt_called")\n'
    )
    subprocess.run(['git', '-C', str(repo), 'add', '.'], check=True)
    subprocess.run(['git', '-C', str(repo), '-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'fixture'], check=True)
    commit = subprocess.check_output(['git', '-C', str(repo), 'rev-parse', 'HEAD'], text=True).strip()
    install = tmp_path / 'install'
    release = install / 'releases' / commit
    release.mkdir(parents=True)
    for item in ('deploy', 'integrations'):
        shutil.copytree(repo / item, release / item)
    (release / '.venv/bin').mkdir(parents=True)
    (release / '.venv/bin/python').symlink_to(sys.executable)
    cache = release / 'integrations/hermes/eimemory/__pycache__'
    cache.mkdir()
    (cache / '__init__.cpython-311.pyc').write_bytes(b'generated bytecode')
    return repo, install, release, commit


@pytest.mark.parametrize('tamper', ['', 'extra_source', 'changed_source'])
def test_receipt_normalizes_only_bytecode_and_rejects_source_drift(tmp_path, tamper):
    repo, install, release, commit = _fixture(tmp_path)
    if tamper:
        shutil.rmtree(release / 'integrations/hermes/eimemory/__pycache__')
    if tamper == 'extra_source':
        (release / 'integrations/hermes/eimemory/unexpected.py').write_text('BAD = True\n')
    elif tamper == 'changed_source':
        (release / 'integrations/hermes/eimemory/__init__.py').write_text('VALUE = 2\n')
    values = {
        'REPO_DIR': str(repo), 'RELEASE_DIR': str(release), 'INSTALL_ROOT': str(install),
        'COMMIT': commit, 'BASELINE_PRIOR_COMMIT': commit, 'CURRENT_LINK': str(install / 'current'),
        'EIMEMORY_HEALTH_URL': 'http://127.0.0.1:1/health', 'PYTHON_BIN': sys.executable,
        'USER_SYSTEMD_ENABLE_SERVICE': '1', 'EIMEMORY_CODE_EVOLUTION_TRANSACTION_MODE': '0',
        'EIMEMORY_ROOT': str(tmp_path / 'runtime'), 'EIMEMORY_CONFIG_DIR': str(tmp_path / 'config'),
        'EVIDENCE_RECEIPT_ENV_FILE': str(tmp_path / 'unused.env'),
        'EIMEMORY_DEPLOY_SCOPE_AGENT': 'test', 'EIMEMORY_DEPLOY_SCOPE_WORKSPACE': 'test',
        'EIMEMORY_DEPLOY_SCOPE_USER': 'test',
    }
    script = '\n'.join(k + '=' + shlex.quote(v) for k, v in values.items()) + '\n'
    script += _function('_prepare_release_receipt_source') + _function('_record_deployment_receipt')
    # Call inside a conditional: bash set -e is disabled here, as in the real
    # post-deploy caller, so every gate must propagate its error explicitly.
    script += 'if _record_deployment_receipt; then exit 0; else exit $?; fi\n'
    env = dict(os.environ, TEST_RELEASE=str(release))
    result = subprocess.run(['bash', '-c', script], env=env, capture_output=True, text=True)
    if tamper:
        assert result.returncode != 0, result.stdout + result.stderr
        assert 'receipt_called' not in result.stdout
        if tamper == 'extra_source':
            assert (release / 'integrations/hermes/eimemory/unexpected.py').exists()
        else:
            assert (release / 'integrations/hermes/eimemory/__init__.py').read_text() == 'VALUE = 2\n'
    else:
        assert result.returncode == 0, result.stdout + result.stderr
        assert 'receipt_called' in result.stdout
        assert not list((release / 'integrations').rglob('__pycache__'))
