"""Tests for LongMemEval evidence mining in the converter.

Background
----------

The previous converter hard-coded ``evidence_turn_ids = []`` and only
populated ``evidence_session_ids`` from ``answer_session_ids``. That made
the LME eval a *ranking* test (any session in the answer set was a hit)
rather than a *retrieval* test (did we surface the specific turns the
answer cites?).

The new converter mines the per-message ``has_answer`` boolean — the
official LongMemEval evidence signal — and turns it into
``evidence_turn_ids`` of the form ``{session_id}:m{msg_idx}`` so the
adapter's set-membership check works end-to-end. It also unions in
``answer_session_ids`` and the top-level ``evidence_session_ids`` /
``evidence_turn_ids`` fields when present (other LongMemEval variants
publish those).

These tests pin:

* ``has_answer`` messages on the raw side produce matching
  ``evidence_turn_ids`` on the eimemory side, for the cleaned variant
  and for synthetic inputs.
* ``answer_session_ids`` continues to flow into
  ``evidence_session_ids`` (no regression on the original wiring).
* The feature flag controls behaviour; disabling it reproduces the
  pre-fix empty-turn-ids behaviour.

The ``data/longmemeval_s_eimemory.json`` snapshot is NOT regenerated by
these tests; the converter is exercised against the raw input only.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONVERTER_PATH = REPO_ROOT / "scripts" / "convert_longmemeval_to_eimemory.py"
DATA_PATH = REPO_ROOT / "data" / "longmemeval_s_cleaned.json"


def _load_converter():
    """Import the converter script as a module (it is in scripts/, not a package)."""
    spec = importlib.util.spec_from_file_location("lme_converter", CONVERTER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


def _load_raw_sample(limit: int = 1) -> list[dict]:
    return _load_json_array_sample(DATA_PATH, limit=limit)


def _load_json_array_sample(path: Path, *, limit: int | None = None) -> list[dict]:
    items: list[dict] = []
    for item in _iter_json_array(path):
        items.append(item)
        if limit is not None and len(items) >= limit:
            break
    return items


def _iter_json_array(path: Path):
    decoder = json.JSONDecoder()
    buffer = ""
    started = False
    with path.open("r", encoding="utf-8") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if chunk:
                buffer += chunk
            while True:
                buffer = buffer.lstrip()
                if not started:
                    if not buffer:
                        break
                    if buffer[0] != "[":
                        raise ValueError(f"expected JSON array in {path}")
                    buffer = buffer[1:]
                    started = True
                    continue
                if not buffer:
                    break
                if buffer[0] == ",":
                    buffer = buffer[1:]
                    continue
                if buffer[0] == "]":
                    return
                try:
                    item, end = decoder.raw_decode(buffer)
                except json.JSONDecodeError:
                    if chunk:
                        break
                    raise
                yield item
                buffer = buffer[end:]
            if not chunk:
                return


# ---------------------------------------------------------------------------
# Required by task spec: at least 2 tests
# ---------------------------------------------------------------------------


def test_lme_converter_emits_real_evidence(tmp_path) -> None:
    """A cleaned-variant raw case must yield non-empty evidence_session_ids."""
    converter = _load_converter()
    raw = _load_raw_sample(limit=1)
    assert raw[0].get("answer_session_ids"), "raw sample missing answer_session_ids"
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 1
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    case = out_data["cases"][0]
    assert case["evidence_session_ids"], "expected non-empty evidence_session_ids"
    # The answer session must be a subset of evidence_session_ids.
    assert set(raw[0]["answer_session_ids"]).issubset(set(case["evidence_session_ids"]))
    # Real turn evidence must be present for the cleaned variant when
    # the raw case has has_answer=True messages. Case 0 has 2.
    assert "evidence_turn_ids" in case
    assert len(case["evidence_turn_ids"]) >= 1, (
        f"expected >= 1 evidence_turn_ids mined from has_answer, got {case['evidence_turn_ids']!r}"
    )
    # Turn IDs must follow the {sid}:m{msg_idx} format the converter
    # also emits on the haystack side — otherwise the adapter's
    # set-membership check will silently miss every hit.
    import re
    turn_id_pattern = re.compile(r"^.+:m\d+$")
    for turn_id in case["evidence_turn_ids"]:
        assert turn_id_pattern.match(turn_id), (
            f"turn_id {turn_id!r} is not in {{sid}}:m{{msg_idx}} format"
        )


def test_lme_converter_evidence_matches_raw(tmp_path) -> None:
    """The eimemory evidence_session_ids must include all raw answer_session_ids."""
    converter = _load_converter()
    raw = _load_raw_sample(limit=3)
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 3
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    for raw_case, eim_case in zip(raw, out_data["cases"]):
        assert set(raw_case.get("answer_session_ids") or []).issubset(
            set(eim_case["evidence_session_ids"])
        ), (
            f"raw answer_session_ids missing from eimemory evidence_session_ids "
            f"for case {raw_case['question_id']}"
        )
        # The eimemory case_id is the raw question_id.
        assert eim_case["case_id"] == raw_case["question_id"]
        # The eimemory question mirrors the raw question.
        assert eim_case["question"] == raw_case["question"]


# ---------------------------------------------------------------------------
# has_answer mining end-to-end (this is the bug fix the verifier was waiting for)
# ---------------------------------------------------------------------------


def test_lme_converter_mines_has_answer_into_turn_ids(tmp_path) -> None:
    """Mining has_answer messages must produce matching evidence_turn_ids."""
    converter = _load_converter()
    raw = [
        {
            "question_id": "has-ans-1",
            "question": "What did I graduate with?",
            "question_type": "single-session-user",
            "question_date": "2023/05/30",
            "answer": "Business Administration",
            "answer_session_ids": ["sess-grad"],
            "haystack_session_ids": ["sess-noise", "sess-grad"],
            "haystack_dates": ["2023-05-01", "2023-05-30"],
            "haystack_sessions": [
                [
                    {"role": "user", "content": "What's a good task app?"},
                    {"role": "assistant", "content": "Try Todoist."},
                ],
                [
                    {"role": "user", "content": "I graduated with a degree in Business Administration."},
                    {"role": "assistant", "content": "Congratulations!"},
                ],
            ],
        }
    ]
    # Patch the second message of the second session with has_answer=True
    # (this is the official LongMemEval evidence signal).
    raw[0]["haystack_sessions"][1][0]["has_answer"] = True
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 1
    case = json.loads(out_path.read_text(encoding="utf-8"))["cases"][0]
    # The mined turn id must reference the actual evidence message.
    assert case["evidence_turn_ids"] == ["sess-grad:m0"], (
        f"expected ['sess-grad:m0'] from has_answer mining, got {case['evidence_turn_ids']!r}"
    )
    # The session that contains the has_answer message must be in
    # evidence_session_ids, on top of the answer_session_ids entry.
    assert "sess-grad" in case["evidence_session_ids"]


def test_lme_converter_mines_multiple_has_answer_messages(tmp_path) -> None:
    """Multiple has_answer messages must all be mined, preserving order."""
    converter = _load_converter()
    raw = [
        {
            "question_id": "has-ans-2",
            "question": "What is the answer?",
            "question_type": "multi-session",
            "answer": "yes",
            "answer_session_ids": ["sess-A"],
            "haystack_session_ids": ["sess-A"],
            "haystack_dates": ["2024-01-01"],
            "haystack_sessions": [
                [
                    {"role": "user", "content": "msg 0", "has_answer": False},
                    {"role": "assistant", "content": "msg 1", "has_answer": True},
                    {"role": "user", "content": "msg 2", "has_answer": False},
                    {"role": "assistant", "content": "msg 3", "has_answer": True},
                ],
            ],
        }
    ]
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    converter.convert(in_path, out_path)
    case = json.loads(out_path.read_text(encoding="utf-8"))["cases"][0]
    assert case["evidence_turn_ids"] == ["sess-A:m1", "sess-A:m3"]


def test_lme_converter_real_cleaned_data_mines_turn_ids() -> None:
    """End-to-end: 500/500 cleaned cases, 95%+ must have turn evidence.

    The 21 abstract-reasoning cases (with ``*_abs`` answer_session_ids
    and no has_answer marks) are the only legitimate zero cases; the
    other 479/500 must produce at least one mined turn id.
    """
    converter = _load_converter()
    # Run the helper directly (no file IO) over every case.
    mined = []
    first_turn_ids: list[str] | None = None
    for case in _iter_json_array(DATA_PATH):
        ses, turns = converter._extract_real_evidence(
            case,
            haystack_session_ids=case.get("haystack_session_ids") or [],
            haystack_sessions=case.get("haystack_sessions") or [],
        )
        mined.append((ses, turns))
        if first_turn_ids is None:
            first_turn_ids = turns
    assert len(mined) == 500
    with_turns = sum(1 for _, turns in mined if turns)
    assert with_turns >= 470, (
        f"expected >= 470/500 cases to have mined turn evidence, got {with_turns}"
    )
    # The first raw case has 2 has_answer messages.
    assert first_turn_ids == ["answer_280352e9:m4", "answer_280352e9:m5"]


# ---------------------------------------------------------------------------
# Synthetic top-level evidence_turn_ids still flows through
# ---------------------------------------------------------------------------


def test_lme_converter_propagates_evidence_turn_ids(tmp_path) -> None:
    """When raw carries top-level evidence_turn_ids, they must flow to eimemory."""
    converter = _load_converter()
    raw = [
        {
            "question_id": "syn-1",
            "question": "When did the user move?",
            "question_type": "temporal",
            "question_date": "2024-01-01",
            "answer": "March 2023",
            "answer_session_ids": ["sess-move"],
            "haystack_session_ids": ["sess-move", "sess-other"],
            "haystack_dates": ["2023-03-01", "2023-04-01"],
            "haystack_sessions": [
                [
                    {"role": "user", "content": "I moved in March 2023."},
                ],
                [
                    {"role": "user", "content": "I had dinner."},
                ],
            ],
            "evidence_turn_ids": ["sess-move:m0"],
        }
    ]
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    n = converter.convert(in_path, out_path)
    assert n == 1
    out_data = json.loads(out_path.read_text(encoding="utf-8"))
    case = out_data["cases"][0]
    assert case["evidence_session_ids"] == ["sess-move"]
    assert "sess-move:m0" in case["evidence_turn_ids"]
    assert case["meta"]["evidence_mining_enabled"] is True


def test_lme_converter_feature_flag_disables_mining(tmp_path, monkeypatch) -> None:
    """With the flag off, evidence_turn_ids is hard-coded empty again."""
    converter = _load_converter()
    monkeypatch.setattr(converter, "_USE_REAL_EVIDENCE", False)
    raw = [
        {
            "question_id": "syn-2",
            "question": "q?",
            "question_type": "temporal",
            "answer": "a",
            "answer_session_ids": ["sess-x"],
            "haystack_session_ids": ["sess-x"],
            "haystack_dates": ["2024-01-01"],
            "haystack_sessions": [
                [{"role": "user", "content": "hi", "has_answer": True}],
            ],
        }
    ]
    in_path = tmp_path / "raw.json"
    out_path = tmp_path / "lme.json"
    in_path.write_text(json.dumps(raw, ensure_ascii=False), encoding="utf-8")
    converter.convert(in_path, out_path)
    case = json.loads(out_path.read_text(encoding="utf-8"))["cases"][0]
    # Flag off -> turn IDs dropped even though raw had has_answer.
    assert case["evidence_turn_ids"] == []
    assert case["meta"]["evidence_mining_enabled"] is False
    # Session-level evidence still flows (it predates the flag).
    assert case["evidence_session_ids"] == ["sess-x"]


def test_lme_converter_extract_real_evidence_helper() -> None:
    """Direct unit test of the extraction helper (no IO)."""
    converter = _load_converter()
    # Both top-level fields populated; helper unions them with dedup.
    ses, turns = converter._extract_real_evidence(
        {
            "answer_session_ids": ["A", "B"],
            "evidence_session_ids": ["B", "C"],
            "evidence_turn_ids": ["t1", "t2"],
        }
    )
    assert ses == ["A", "B", "C"]
    assert turns == ["t1", "t2"]
    # Only answer_session_ids.
    ses, turns = converter._extract_real_evidence({"answer_session_ids": ["only"]})
    assert ses == ["only"]
    assert turns == []
    # Empty case.
    assert converter._extract_real_evidence({}) == ([], [])
    # has_answer mining via the haystack path.
    ses, turns = converter._extract_real_evidence(
        {},
        haystack_session_ids=["s1"],
        haystack_sessions=[
            [
                {"role": "u", "content": "noise"},
                {"role": "u", "content": "evidence", "has_answer": True},
            ],
        ],
    )
    assert ses == ["s1"]
    assert turns == ["s1:m1"]
